/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MODERF
#define MODERF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class modErf : public RooAbsPdf {
public:
  modErf() {} ; 
  modErf(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _cutoff,
	      RooAbsReal& _shift,
	      RooAbsReal& _shrink);
  modErf(const modErf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new modErf(*this,newname); }
  inline virtual ~modErf() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  Double_t evaluate() const ;
protected:

  RooRealProxy x ;
  RooRealProxy cutoff ;
  RooRealProxy shift ;
  RooRealProxy shrink ;
  

private:

  ClassDef(modErf,1) // Your description goes here...
};
 
#endif
