/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

#ifndef POWERLAW
#define POWERLAW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class PowerLaw : public RooAbsPdf {
public:
  PowerLaw() {} ;
  PowerLaw(const char *name, const char *title,
          RooAbsReal& _x,
          RooAbsReal& _k);
  PowerLaw(const PowerLaw& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new PowerLaw(*this,newname); }
  inline virtual ~PowerLaw() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

protected:

  RooRealProxy x ;
  RooRealProxy k ;

  Double_t evaluate() const ;

private:

  // ClassDef(PowerLaw,1) // Your description goes here...
};

#endif
