/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef XICSTBG
#define XICSTBG

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class XicstBG : public RooAbsPdf {
public:
  XicstBG() {} ; 
  XicstBG(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _a,
	      RooAbsReal& _b,
	      RooAbsReal& _power,
	      RooAbsReal& _cutoff);
  XicstBG(const XicstBG& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new XicstBG(*this,newname); }
  inline virtual ~XicstBG() { }

  Int_t getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* rangeName=0) const ;
  Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const ;

  Double_t evaluate() const ;
protected:

  RooRealProxy m ;
  RooRealProxy a ;
  RooRealProxy b ;
  RooRealProxy power ;
  RooRealProxy cutoff ;
  

private:

  ClassDef(XicstBG,1) // Your description goes here...
};
 
#endif
