# METHODS = ["BDTG", "MLP", "BDTF"]
METHODS =[""]
PUNZI_CUT = 0.0001

rule compile_classification:
    input:
        "TMVAClassification.C",
        "makefile"
    output:
        "TMVAClassification",
    threads: 1
    log: ".snakemake_logs"
    shell:
        "make -j{threads} TMVAClassification >> {log}"


rule compile_application:
    input:
        "TMVAClassificationApplication.C",
        "makefile"
    output:
        "TMVAClassificationApplication",
    threads: 1
    log: ".snakemake_logs"
    shell:
        "make -j{threads} {output} >> {log}"

rule run_classification:
    input:
        feature_set = "feature_sets/set{set_number}.json",
        app = "TMVAClassification"
    output:
        "runs/run_fs{set_number}_hp{hp_number}/TMVA.root",
        directory("runs/run_fs{set_number}_hp{hp_number}/dataset")
    log:
        "runs/run_fs{set_number}_hp{hp_number}/logs/classification_output.log"
    threads: 2
    shell:
        "./scripts/run_classification.sh -f{wildcards.set_number} -h{wildcards.hp_number} {METHODS} > {log}"

rule run_application:
    input:
        "feature_sets/set{set_number}.json",
        "TMVAClassificationApplication",
        "runs/run_fs{set_number}_hp{hp_number}/TMVA.root"
    output:
        "runs/run_fs{set_number}_hp{hp_number}/TMVApp.root"
    log:
        "runs/run_fs{set_number}_hp{hp_number}/logs/application_output.log"
    threads: 1
    shell:
        "./scripts/run_application.sh -f{wildcards.set_number} -h{wildcards.hp_number} {METHODS} > {log}"


rule run_punzi_analysis:
    input:
        "runs/run_fs{set_number}_hp{hp_number}/TMVA.root",
        "get_punzi.C"
    output:
        directory("runs/run_fs{set_number}_hp{hp_number}/punzi")
    threads: 1
    log: "runs/run_fs{set_number}_hp{hp_number}/punzi/log.txt"
    shell:
        "./scripts/run_punzi.sh -f{wildcards.set_number} -h {wildcards.hp_number} > {log}"

rule run_punzi_cut_analysis:
    input:
        "runs/run_fs{set_number}_hp{hp_number}/TMVA.root",
        "get_punzi.C"
    output:
        directory("runs/run_fs{set_number}_hp{hp_number}/punzi_cut")
    threads: 1
    log: "runs/run_fs{set_number}_hp{hp_number}/punzi_cut/log.txt"
    shell:
        "./scripts/run_punzi.sh -f{wildcards.set_number} -h {wildcards.hp_number} -c {PUNZI_CUT} > {log}"
